# generated by datamodel-codegen:
#   filename:  payload.json.schema
#   timestamp: 2025-03-04T13:20:43+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import Field

from jinja_cv.models.new_models import DefaultBaseModel as BaseModel
from dataclasses import dataclass

@dataclass(init=False)
class IExperience():
    contexte: str
    environnement: str
    realisations: str
    resultats: str
    entreprise: str
    titre: str
    debut: str
    fin: str
    duree: str

@dataclass(init=False)
class Experience(IExperience, BaseModel):
    pass

class Diplome(BaseModel):
    hidden: bool
    id: str
    diplome: str
    ecole: Optional[str]
    index: None

@dataclass(init=False)
class AllMobility():
    Id: str = None
    Name: str = None
    ParentId: Optional[str] = None

@dataclass(init=False)
class IDossier():
    id: str
    key: str
    nom: str
    prenom: str
    hide_prenom: bool
    hide_annees_experience: bool
    language: str
    brand: str
    keywords: str
    introduction: str
    competences_techniques: str
    connaissances: str
    secteurs_activite: None
    qualites: None
    qualite1: None
    qualite2: None
    qualite3: None
    qualite4: None
    background: None
    strength: None
    growth: None
    reglementations: None
    specialites: None
    scope_intervention: None
    formes_galeniques: None
    equipements: None
    languages_skills: List
    experiences: List[Experience]
    missions: List
    diplomes: List[Diplome]
    formations: List
    education_at_the_end: bool
    mobilities: List[str]
    all_mobilities: List[AllMobility]
    email: str
    metier: str
    annees_experience: str
    brandByDefault: bool
    communicationLanguage: str
    gender: str
    generateBlankBrand: bool
    templateType: None = None
    isConsultant: bool = True
    
class Dossier(IDossier, BaseModel):

    generate_blank_brand: bool = Field(..., alias='generateBlankBrand')
    template_type: None = Field(..., alias='templateType')
    is_consultant: bool = Field(..., alias='isConsultant')
    brand_by_default: bool = Field(..., alias='brandByDefault')
    communication_language: str = Field(..., alias='communicationLanguage')
    
@dataclass(init=False)
class DDossier(IDossier):
    pass

@dataclass(init=False)
class IModel(BaseModel):
    dossier: Dict
    removedDiplomes: List[str] = []
    removedFormations: List[str] = []
    removedExperiences: List[str] = []
    closeAccess: bool = False

class Model(BaseModel):
    dossier: Dossier
    removed_diplomes: List = Field(..., alias='removedDiplomes')
    removed_formations: List = Field(..., alias='removedFormations')
    removed_experiences: List = Field(..., alias='removedExperiences')
    close_access: bool = Field(..., alias='closeAccess')

